export const mockTransactions = [
  {
    id: 1,
    type: "income",
    category: "Penjualan Produk",
    description: "Penjualan 15 unit Produk A",
    amount: 3750000,
    date: "2025-01-06",
    paymentMethod: "bank_transfer",
    notes: "Pembayaran dari PT ABC",
  },
  {
    id: 2,
    type: "expense",
    category: "Pembelian Bahan Baku",
    description: "Pembelian bahan baku untuk produksi",
    amount: 2500000,
    date: "2025-01-05",
    paymentMethod: "cash",
    notes: "",
  },
  {
    id: 3,
    type: "income",
    category: "Penjualan Jasa",
    description: "Jasa konsultasi bisnis",
    amount: 5000000,
    date: "2025-01-05",
    paymentMethod: "bank_transfer",
    notes: "Klien: CV XYZ",
  },
  {
    id: 4,
    type: "expense",
    category: "Gaji Karyawan",
    description: "Gaji bulan Januari 2025",
    amount: 8000000,
    date: "2025-01-04",
    paymentMethod: "bank_transfer",
    notes: "5 karyawan",
  },
  {
    id: 5,
    type: "expense",
    category: "Sewa Tempat",
    description: "Sewa toko bulan Januari",
    amount: 3000000,
    date: "2025-01-03",
    paymentMethod: "bank_transfer",
    notes: "",
  },
  {
    id: 6,
    type: "income",
    category: "Penjualan Produk",
    description: "Penjualan 8 unit Produk B",
    amount: 4800000,
    date: "2025-01-03",
    paymentMethod: "e_wallet",
    notes: "",
  },
]
